- name: "Setup Argocd"
  hosts: all
  vars_files:
    - vars.yml
  vars:
    # https://github.com/argoproj/argo-helm/blob/master/charts/argo-cd/values.yaml#L33
    # https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/
    kubernetes_spices_argocd_host_aliases: []
  roles:
    - role: kameshsampath.kubernetes_spices.argocd
  tasks:
    - name: Include gitea_details
      include_vars: 
        file: "{{ work_dir }}/gitea_details.yaml"
        name:  kubernetes_spices_gitea_details
      when: kubernetes_spices_gitea_add_host_aliases
   
    # - debug: 
    #    var: kubernetes_spices_gitea_details

    - name: Add gitea hosts to argocd host aliases list
      set_fact:
        kubernetes_spices_argocd_host_aliases:  "{{ kubernetes_spices_argocd_host_aliases + kubernetes_spices_gitea_details.kubernetes_spices_gitea_host_aliases }}"
      when: kubernetes_spices_gitea_details is defined
       
    - name: Add argo-cd to use host aliases
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/argocd/values.yaml.j2"
        dest: "{{ work_dir }}/argocd-values.yaml"
        variable_start_string: '[['
        variable_end_string: ']]'
      when: kubernetes_spices_argocd_host_aliases | length > 0
      register: kubernetes_spices_argocd_host_aliased_values

    - name: "Rollout updates to Argocd"
      kubernetes.core.helm:
        release_name: argocd
        chart_ref: argo/argo-cd
        release_namespace: "{{ kubernetes_spices_argocd_namespace }}"
        create_namespace: yes
        chart_version: "{{ kubernetes_spices_argocd_chart_version }}"
        values_files:
            - "{{ work_dir }}/argocd-values.yaml"
        update_repo_cache: yes
        context: "{{ kubernetes_spices_argocd_k8s_context }}"
        wait: yes
      when: kubernetes_spices_argocd_host_aliased_values.changed

    - name: "Create quay.io token secret"
      kubernetes.core.k8s:
        state: present
        definition:
          kind: Secret
          apiVersion: v1
          metadata:
            namespace: argocd
            name: quay-io
          data:
            username: "{{ lookup('env', 'QUAYIO_USERNAME') | b64encode }}"
            token: "{{ lookup('env', 'QUAYIO_PASSWORD') | b64encode }}"
        context: "{{ kubernetes_spices_argocd_k8s_context }}"

    - name: "Configure Image Updater Registries"
      kubernetes.core.k8s:
        state: patched
        context: "{{ kubernetes_spices_argocd_k8s_context }}"
        kind: ConfigMap
        name: argocd-image-updater-config
        namespace: argocd
        definition:
          data:
            registries.conf: |
              registries:
                - name: quay
                  prefix: quay.io
                  api_url: https://quay.io
                  ping: yes
                  defaultns: kameshsampath
                  tagsortmode: latest-first
                  credentials: secret:argocd/quay-io#token

    - name: "direnv allow"
      ansible.builtin.command:
        argv:
          - direnv
          - allow
          - "{{ playbook_dir }}"
