- name: "Setup Gitea"
  hosts: all
  vars_files:
    - vars.yml
  
  roles:
   - role: kameshsampath.kubernetes_spices.gitea
  
  tasks:
    - name: "direnv allow"
      ansible.builtin.command:
        argv:
          - direnv
          - allow
          - "{{ playbook_dir }}"
