- name: "Deploy Gloo Edge and Gloo Portal"
  hosts: all
  vars_files:
    - vars.yml
  roles:
    - role: kameshsampath.gloo.edge
  tasks:

    - name: "direnv allow"
      ansible.builtin.command:
        argv:
          - direnv
          - allow
          - "{{ playbook_dir }}"