- name: "Setup Gitea"
  hosts: all
  vars_files:
    - vars.yml
  vars:
    regen_certs: true

  roles:
   # - name: acme
   - name: kameshsampath.kubernetes_spices.gitea
  
  tasks:
    
    # - name: "Get Gloo Proxy HTTP Address"
    #   kubernetes.core.k8s_info:
    #     kind: Service
    #     name:  gateway-proxy
    #     namespace: "{{ kubernetes_spices_gitea_namespace  }}"
    #     context: "{{ kubernetes_spices_gitea_k8s_context }}"
    #   register: gateway_proxy_http_svc_result
  
    - name: "Slurp SSL Certificate"
      ansible.builtin.slurp:
        src: "{{ kubernetes_spices_tls_cert_path }}"
      register: gitea_tls_cert_b64

    - name: "Slurp SSL private key"
      ansible.builtin.slurp:
        src: "{{ kubernetes_spices_tls_key_path }}"
      register: gitea_tls_key_b64
  
    - name: "Create Gitea TLS Secret"
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: gitea-upstream-tls
            namespace: "{{ kubernetes_spices_gitea_namespace  }}"
          type: kubernetes.io/tls
          data:
            tls.key: "{{ gitea_tls_key_b64['content'] }}"
            tls.crt: "{{ gitea_tls_cert_b64['content'] }}"

    ## Overrides
    - name: "Query Git url"
      kubernetes.core.k8s_info:
        kind: Service
        name: gateway-proxy
        namespace: "{{ kubernetes_spices_gitea_namespace  }}"
        context: "{{ kubernetes_spices_gitea_k8s_context }}"
      register: git_service_result

    - name: Set Gitea Facts
      set_fact:
        gitea_version: "{{ gitea_version_info.stdout  | from_json | first | community.general.json_query('version') }}"
        git_url: "https://gitea.{{ git_service_result.resources[0] | json_query(q) | first }}.{{ kubernetes_spices_acme_dns_zone }}"
        gitea_service_lb_ip: "{{ git_service_result.resources[0] | json_query(q) | first }}"
      when: gitea_version is not defined
      vars:
        q: "status.loadBalancer.ingress[*].ip"

    - name: Set Gitea DNS facts
      set_fact:
        gitea_dns_name: "gitea.{{ gitea_service_lb_ip }}.{{ kubernetes_spices_acme_dns_zone }}"

    - name: "Gitea Version"
      debug: 
        var: gitea_version

    - name: "Generate Gitea config"
      ansible.builtin.template:
        src: "{{ playbook_dir }}/templates/gitea-gloo/gitea-values.yaml.j2"
        dest: "{{ work_dir }}/gitea-values.yaml"
 
    - name: "Update Gitea deployment"
      kubernetes.core.helm:
        release_name: gitea
        chart_ref: gitea-charts/gitea
        release_namespace: "{{ kubernetes_spices_gitea_namespace }}"
        create_namespace: yes
        chart_version: "{{ gitea_version }}"
        values_files:
            - "{{ work_dir }}/gitea-values.yaml"
        update_repo_cache: yes
        context: "{{ kubernetes_spices_gitea_k8s_context }}"
        wait: yes

    # Gitea external access
    - name: "Create/Update Gitea Upstream and Route"
      kubernetes.core.k8s:
        template: 
          - path: "{{ playbook_dir }}/template/gitea-gloo/gitea-upstream.yaml.j2"
          - path: "{{ playbook_dir }}/template/gitea-gloo/gitea-virtual-service.yaml.j2"
        context: "{{ kubernetes_spices_gitea_k8s_context }}"
        namespace: "{{ kubernetes_spices_gitea_namespace  }}"
        state: present
  
    - name: "Set Gitea Service Facts"
      set_fact:
        git_url: "https://gitea.{{ gitea_service_lb_ip }}.{{ kubernetes_spices_acme_dns_zone }}"
      vars:
        q: "status.loadBalancer.ingress[*].ip"

    - name: "Set Gitea Repo Facts"
      set_fact:
        git_repo_fqn: "https://gitea.{{ gitea_service_lb_ip }}.{{ kubernetes_spices_acme_dns_zone }}/{{ gitea_admin_user.username }}/{{ github_template_repo | basename }}"
        gitea_repo_name: "{{ github_template_repo | basename }}"
      when: github_template_repo is defined

    - name: "Clone the template repo from github"
      ansible.builtin.uri:
        url: "{{ git_url }}/api/v1/repos/migrate"
        user: "{{ gitea_admin_user.username }}"
        password: "{{ gitea_admin_user.password }}"
        method: POST
        body:
          clone_addr: '{{ github_template_repo }}'
          uid: 1
          repo_name: "{{ gitea_repo_name }}"
        return_content: yes
        status_code: 
          - 200
          - 201
        body_format: json
        validate_certs: no
        force_basic_auth: yes
      register: clone_repo_result
      when: github_template_repo is defined

    - name: "Add demo origin to current git repo"
      ansible.builtin.command:
        argv:
          - git
          - remote
          - add
          - demo
          - "{{ git_repo_fqn }}"
      when: github_template_repo is defined and not clone_repo_result.failed

    - name: "Dump Gitea Repo Details"
      ansible.builtin.copy:
        dest: "{{ work_dir }}/gitea_details.yaml"
        content: |
            gitea_url: {{ git_url }}
            gitea_credentails: {{ gitea_admin_user }}

    - name: "Checking if .envrc file exists"
      ansible.builtin.stat:
        path: "{{ work_dir }}/.envrc"
      register: st_envrc_file

    - name: "Checking if .envrc file exists"
      ansible.builtin.blockinfile:
        path: "{{ work_dir }}/.envrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK GITEA"
        block: |
          export GITEA_USERNAME="{{ gitea_admin_user.username }}"
          export GITEA_PASSWORD="{{ gitea_admin_user.password }}"
      when: st_envrc_file.stat.exists
    
    - name: "direnv allow"
      ansible.builtin.command:
        argv:
          - direnv
          - allow
          - "{{ playbook_dir }}"
      