---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-fruits-api-trigger-template
  namespace: default
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: main
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: fruits-api-
        labels:
          tekton.dev/pipeline: fruits-api-deploy
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: fruits-api-deploy
        params:
          - name: github-repo-url
            value: '$(tt.params.gitrepositoryurl)'
          - name: github-repo-revision
            value: '$(tt.params.gitrevision)'
          - name: image-name
            value: example.com/kameshsampath/fruits-api
        workspaces:
          - name: maven-settings
            configmap:
              name: maven-settings
          - name: git-source
            persistentVolumeClaim:
              claimName: fruits-api-git-source