---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: gitea-triggerbinding
  namespace: default
spec:
  params:
    - name: gitrevision
      value: $(body.after)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: imageName
      value: 'registry-192.168.64.80.nip.io/kameshsampath/fruits-api'