apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fruits-api
  annotations:
    argocd-image-updater.argoproj.io/image-list: "fruitsapi=registry-192.168.64.80.nip.io/kameshsampath/fruits-api:^[0-9]$"
    argocd-image-updater.argoproj.io/fruitsapi.update-strategy: digest
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: charts/fruits-api
    # update this to your fork
    repoURL: 'https://gitea-192.168.64.81.nip.io/gitea/fruits-api-gitops'
    targetRevision: HEAD
    helm:
      parameters: [ ]
      valueFiles:
        - ../../helm_vars/fruits-api/values.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
