apiVersion: v2
name: fruits-api
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: '10.13.9'
    repository: https://charts.bitnami.com/bitnami
     
     
     

