apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fruits-api-pipelines
  namespace: default
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: pipelines
    # update this to your fork
    repoURL: 'https://gitea-192.168.64.81.nip.io/gitea/fruits-api-gitops'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
