apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: openshift-client-binding
subjects:
  - kind: ServiceAccount
    name: openshift-client-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: openshift-client-role
  apiGroup: rbac.authorization.k8s.io