apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: el-gitea-webhook-http-8080
  namespace: gloo-system
spec:
  kube:
    selector:
      app: el-gitea-webhook
    serviceName: default
    serviceNamespace: el-gitea-webhook
    servicePort: 8080