apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fruits-api-deploy
spec:
  params:
    - name: contextDir
      description: the context directory from where to build the application
      default: .
    - name: git-url
      description: the git repository source url
    - name: git-revision
      description: the git revision to use
      default: main
    - name: image-name
      description: the built container image name
    - name: path-to-image-context
      description: the context directory from where to build the application
      default: .
    - name: path-to-dockerfile
      description: the built container image name
      default: src/main/docker/Dockerfile.jvm
    - name: git-ssl-verify
      description: >-
        to verify ssl ceritificates, for local gitea repos set to false
      default: "false"
  workspaces:
    - name: git-source
    - name: maven-settings
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: sslVerify
          value: $(params.git-ssl-verify)
      workspaces:
        - name: output
          workspace: git-source
    - name: build-and-test-app
      taskRef:
        name: maven
      runAfter:
        - fetch-repo
      params:
        - name: GOALS
          value:
            - -B
            - clean
            - test
      workspaces:
        - name: source
          workspace: git-source
        - name: maven-settings
          workspace: maven-settings
    - name: build-app
      taskRef:
        name: maven
      runAfter:
        - build-and-test-app
      params:
        - name: GOALS
          value:
            - -B
            - -DskipTests
            - clean
            - package
      workspaces:
        - name: source
          workspace: git-source
        - name: maven-settings
          workspace: maven-settings
    - name: compute-image-tag
      runAfter:
        - build-app
      params:
        - name: CONTEXT_DIR
          value: "$(params.contextDir)"
      taskSpec:
        params:
          - name: CONTEXT_DIR
            description: The directory where pom.xml is available
        steps:
          - name: maven-exec
            image: gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
            command: [ "/usr/bin/mvn" ]
            workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
            args:
              - -s
              - $(workspaces.maven-settings.path)/settings.xml
              - '-q'
              - '-Dexec.executable=echo'
              - '-Dexec.args=${project.version}'
              - '--non-recursive'
              - 'exec:exec'
        workspaces:
          - name: source
          - name: maven-settings
        results:
          - name: POM-VERSION
      workspaces:
        - name: source
          workspace: git-source
        - name: maven-settings
          workspace: maven-settings
    - name: build-image
      taskRef:
        name: kaniko
      runAfter:
        - compute-image-tag
      params:
        - name: IMAGE
          value: "$(params.image-name):$(tasks.compute-image-tag.results.POM-VERSION)"
        - name: CONTEXT
          value: $(params.path-to-image-context)
        - name: DOCKERFILE
          value: $(params.path-to-dockerfile)
        - name: EXTRA_ARGS
          value:
            - "--insecure"
      workspaces:
        - name: source
          workspace: git-source
 