namespace: default

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: maven-settings
    files:
      - settings.xml
resources:
  - github-credentials.yaml
  - quayio-credentials.yaml
  - rbac
  - git-source-pvc.yaml
  - pom-version-task.yaml
  - fruits-api-pipeline.yaml

  