apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fruits-api-git-source
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: maven-settings-xml
data:
  settings.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd">
      <localRepository>/tekton/home/.m2</localRepository>
      <mirrors>
        <mirror>
          <id>central</id>
          <name>central</name>
          <url>http://nexus.default:8081/repository/maven-public/</url>
          <mirrorOf>*</mirrorOf>
        </mirror>
      </mirrors>
    </settings>
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: m2-cache
spec:
  workspaces:
    - name: git-source
    - name: maven-settings
  tasks:
    - name: fetch-repo
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/kameshsampath/fruits-api
        - name: deleteExisting
          value: "true"
      workspaces:
        - name: output
          workspace: git-source
    - name: warm-up-m2-repo
      taskRef:
        name: maven
      runAfter:
        - fetch-repo
      params:
        - name: GOALS
          value:
            - -B
            - clean
            - package
      workspaces:
        - name: source
          workspace: git-source
        - name: maven-settings
          workspace: maven-settings
--- 
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: m2-cache-pipeline-run
spec:
  pipelineRef:
    name: m2-cache
  workspaces:
    - name: maven-settings
      configmap:
        name: maven-settings-xml
    - name: git-source
      persistentVolumeClaim:
        claimName: fruits-api-git-source