apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pom-version
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le"
spec:
  description: >
    The task that is used to get the POM version of the maven project that will be built as part of the pipeline or Task
  params:
    - name: CONTEXT_DIR
      description: the context to find pom.xml
      default: .
    - name: MAVEN_IMAGE
      type: string
      description: Maven base image
      default: gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641 #tag: latest
  steps:
    - name: maven-exec
      image: "$(params.MAVEN_IMAGE)"
      workingDir: "$(workspaces.source.path)/$(params.CONTEXT_DIR)"
      script: |
        /usr/bin/mvn \
          org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate \
          -s $(workspaces.maven-settings.path)/settings.xml \
          -q \
          -Dexpression=project.version \
          -Doutput=/tekton/results/POM-VERSION
        echo "POM version of the project: $(cat /tekton/results/POM-VERSION)"
  workspaces:
    - name: source
    - name: maven-settings
  results:
    - name: POM-VERSION
      description: "the pom version of the project available at /workspace/$CONTEXT_DIR"