apiVersion: v1
kind: Secret
metadata:
  name: quay-io
  annotations:
    tekton.dev/docker-0: https://quay.io
type: kubernetes.io/basic-auth
stringData:
  username: ${QUAYIO_USERNAME}
  password: ${QUAYIO_PASSWORD}
