---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: tekton-fruits-api-trigger-template
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: staging
    - name: gitrepositoryurl
      description: The git repository url
    - name: imagename
      description: The container image name
    - name: gitsslverify
      description: TLS verification for git url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: fruits-api-
        labels:
          tekton.dev/pipeline: fruits-api-deploy
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: fruits-api-deploy
        params:
          - name: git-url
            value: '$(tt.params.gitrepositoryurl)'
          - name: git-revision
            value: '$(tt.params.gitrevision)'
          - name: image-name
            value: '$(tt.params.imagename)'
          - name: git-ssl-verify
            value: '$(tt.params.gitsslverify)'
        workspaces:
          - name: maven-settings
            configmap:
              name: maven-settings
          - name: git-source
            persistentVolumeClaim:
              claimName: fruits-api-git-source