---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  # Cluster Roles
  - cluster-role.yaml
  # ROLES
  - tekton-triggers-role-minimal.yaml
  - tekton-triggers-clusterrole-minimal.yaml
  - tekton-triggers-webhook.yaml
  #ROLE Bindings
  - role-bindings.yaml
  # Cluster Role Bindings
  - cluster-role-binding.yaml
