---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tt-minimal
rules:
  # EventListeners need to be able to fetch all namespaced resources
  - apiGroups: [ "triggers.tekton.dev" ]
    resources: [ "clusterinterceptors","eventlisteners", "triggerbindings", "triggertemplates", "triggers" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    # secrets are only needed for GitHub/GitLab interceptors
    # configmaps is needed for updating logging config
    resources: [ "configmaps", "secrets" ]
    verbs: [ "get", "list", "watch" ]
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: [ "tekton.dev" ]
    resources: [ "pipelineruns", "pipelineresources", "taskruns" ]
    verbs: [ "create" ]
  - apiGroups: [ "" ]
    resources: [ "serviceaccounts" ]
    verbs: [ "impersonate" ]
  - apiGroups: [ "policy" ]
    resources: [ "podsecuritypolicies" ]
    resourceNames: [ "tekton-triggers" ]
    verbs: [ "use" ]