kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tt-clusterrole-minimal
rules:
  # EventListeners need to be able to fetch any clustertriggerbindings
  - apiGroups: [ "triggers.tekton.dev" ]
    resources: [ "clusterinterceptors","clustertriggerbindings" ]
    verbs: [ "get", "list", "watch" ]