{{- if .Values.enablePortal -}}
apiVersion: portal.gloo.solo.io/v1beta1
kind: APIDoc
metadata:
  name: {{ include "fruits-api.fullname" . }}-apidoc-v1
  labels:
    {{- include "fruits-api.labels" . | nindent 4 }}
spec:
  openApi:
    content:
      fetchUrl: "http://{{ include "fruits-api.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8080/swagger.json"
{{- end }}