{{- if .Values.enablePortal -}}
apiVersion: portal.gloo.solo.io/v1beta1
kind: APIProduct
metadata:
  name: {{ include "fruits-api.fullname" . }}
  labels:
    {{- include "fruits-api.labels" . | nindent 4 }}
spec:
  displayInfo:
    title: Fruits Product
    description: API Product for Fruits service
  versions:
    - name: v1
      apis:
        - apiDoc:
            name: {{ include "fruits-api.fullname" . }}-apidoc-v1
            namespace: {{ .Release.Namespace }}
      gatewayConfig:
        route:
          inlineRoute:
            backends:
              - upstream:
                  name: {{ .Release.Namespace }}-{{ include "fruits-api.fullname" . }}-8080
                  namespace: gloo-system
{{- end }}