apiVersion: portal.gloo.solo.io/v1beta1
kind: APIProduct
metadata:
  name: fruits-product
  labels:
    {{- include "fruits-api.labels" . | nindent 4 }}
spec:
  displayInfo:
    title: Fruits Product
    description: API Product for Fruits service
  versions:
    - name: v1
      apis:
        - apiDoc:
            name: apidoc-v1-fruits
            namespace: default
      gatewayConfig:
        route:
          inlineRoute:
            backends:
              - upstream:
                  name: default-{{ include "fruits-api.fullname" . }}-8080
                  namespace: gloo-system
