{{- if .Values.enableRBAC -}}
apiVersion: v1
kind: Secret
metadata:
  name: dev1-password
  namespace: gloo-portal
  labels:
    {{- include "fruits-api.labels" . | nindent 4 }}
type: Opaque
data:
  # password: mysecurepassword
  password: JDJ5JDEwJHAyeVowV2p0R3h0WnM2V1NwNVhxQnV2U0hDZC9ORDlxY2tMSnYyZEhrZktKTjdKN0tHLmU2Cg==
{{- end }}