apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-schema
data:
  init-schema.sql: |
    CREATE TABLE public.fruits
    (
        id          bigint                   NOT NULL,
        name        text                     NOT NULL,
        season      text                     NOT NULL,
    );

    ALTER TABLE public.fruits
        OWNER TO {{ .Values.postgresql.global.postgresql.postgresqlUsername }};

    CREATE SEQUENCE public.fruits_id_seq
        AS bigint
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1;

    ALTER TABLE public.fruits_id_seq
        OWNER TO {{ .Values.postgresql.global.postgresql.postgresqlUsername }};

    ALTER SEQUENCE public.fruits_id_seq OWNED BY public.fruits.id;

    ALTER TABLE ONLY public.fruits
        ALTER COLUMN id SET DEFAULT nextval('public.fruits_id_seq'::regclass);

    ALTER TABLE ONLY public.fruits
        ADD CONSTRAINT fruits_pkey PRIMARY KEY (id);